### PR TITLE
Include redundant links when calculate collision

### PR DESCRIPTION
**Pull request by chiwunau**
This is to fix the problem discussed in https://github.com/jsk-ros-pkg/jsk_pr2eus/issues/206

### CODE REVIEW

**Comment by k-okada** [comment]
@h-kamada please check if this PR is OK for you.

**Comment by h-kamada** [comment]
The code itself seems ok.

I faced the collision problem when I was writing about `:start-grasp` , `stop-grasp` method of `*pr2*`.
Currently  `:start-grasp` is checking grasp by checking collisions of all gripper links. ( --> https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/pr2-utils.l#L263-L272)

I forgot details about this , but  I think the problem was that `pqp-collision-check` didn't work well if I used `(pqp-collision-check *pr2* target)`.
So I tried to check whether I can use `(pqp-collision-check *pr2* target)` if I use this code.
But the original code also worked well (not knowing why). 
So I couldn't check whether this code is ok for my problem.

**Comment by chiwunau** [comment]
In this PR (may be there is better solution), collision models are basically attached to their ascendant link found in eus model link-list, so gripper link consider as wrist_roll_link.
which means ```(pqp-collision-check (elt (send *pr2* :larm :links) 6) cube)``` returns 1 in the picture below.
So the original code may be needed to specify only gripper.
screenshot_from_2016-06-15 19 24 39

**Comment by k-okada** [comment]
@snozawa , @YoheiKakiuchi  could take a look at this PR and check if we can import this code into irteus level

**Pull request merged**
