### PR TITLE
Remove packages from .rosinstall on travis

### PR DESCRIPTION
**Pull request by garaemon**

### CODE REVIEW

**Comment by garaemon** [comment]
```
FAILURE: Test node [roseus/roseus] does not exist or is not executable
```

**Comment by garaemon** [comment]
roseus executable is not installed???

**Comment by k-okada** [comment]
this is overwritten by #91

**Comment by k-okada** [comment]
humm that is strange, roseus is installed, so it is strange....

**Comment by garaemon** [comment]
need to re-source bashrc?

✉︎ Ryohei

**Pull request closed without merging**
