### PR TITLE
Add option to thin out trajectories in time

### PR DESCRIPTION
**Pull request by 708yamaguchi**
I am currently running kinova arm with MoveIt!.

Since kinova arm only accepts interpolated trajectories every 1ms, it is necessary to interpolate the trajectories returned by Moveit on the roseus side.

If there are many interpolation points in the trajectory returned by moveit, the interpolation calculation will take a long time, so the thinning option is useful.

Related to https://github.com/jsk-ros-pkg/jsk_robot/pull/1313#issuecomment-872087823

### CODE REVIEW

**Comment by k-okada** [comment]
@708yamaguchi could you provide simplest example code which reproduce the problem?

**Review by k-okada — CHANGES_REQUESTED** [review]
@708yamaguchi could you provide simplest example code which reproduce the problem?

**Comment by 708yamaguchi** [comment]
Here is example code to reproduce this problem (I am sorry that the example code is complicated. This is because I need to use https://github.com/jsk-ros-pkg/jsk_robot/pull/1372 )

However, I found `sample_duration` param in move_group, which can control the interpolation intervals in MoveIt! trajectory. So actually this PR is no more needed.
Move to https://github.com/jsk-ros-pkg/jsk_robot/pull/1373

```
# Setup
mkdir -p ~/kinova_ws/src
cd ~/kinova_ws/src
wstool init
wstool merge https://raw.githubusercontent.com/708yamaguchi/jsk_robot/reflect-kinova-upstream/jsk_kinova_robot/kinova.rosinstall
wstool update
cd jsk_robot
git remote add 708yamaguchi https://github.com/708yamaguchi/jsk_robot.git
git fetch 708yamaguchi
git checkout -t 708yamaguchi/reflect-kinova-upstream
cd ../..
source /opt/ros/melodic/setup.bash
rosdep install -y -r --from-paths src --ignore-src
catkin build jsk_kinova_startup kinovaeus
source devel/setup.bash

# Terminal 1
roslaunch kortex_gazebo spawn_kortex_robot.launch arm:=gen3_lite gripper:=gen3_lite_2f robot_name:=arm_gen3

# Terminal 2
roscd kinovaeus
roseus kinova-interface.l
(kinova-init :type :gen3_lite_gen3_lite_2f)
(send *ri* :angle-vector (send *kinova* :init-pose) 20000)
```

**Comment by 708yamaguchi** [comment]
I am sorry for the confusion.
This PR is no more needed because https://github.com/jsk-ros-pkg/jsk_robot/pull/1373 is merged.

**Pull request closed without merging**
