### PR TITLE
[pr2eus] Use get-topics in speak.l to check whether already advertise…

### PR DESCRIPTION
**Pull request by aginika**
…d or not

from https://github.com/start-jsk/2014-semi/issues/464

### CODE REVIEW

**Comment by k-okada** [comment]
please merge https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/137 if passed

**Comment by k-okada** [comment]
please merge origin/master

**Comment by aginika** [comment]
I did

**Comment by k-okada** [comment]
thanks

**Pull request merged**
