### PR TITLE
[pr2eus_tutorials] add pr2 tabletop demo test and sample

### PR DESCRIPTION
**Pull request by knorth55**
I updated #217 and work in PR2 indigo.
@k-okada We want to use this tutorials this Monday. Can you review and merge this?

### CODE REVIEW

**Comment by k-okada** [comment]
Sorry, but since someone brakes pcl_ros, I think travis will not pass this
PR until monday, So until they fixed pcl_ros, I think you can start with
https://github.com/jsk-enshu/robot-programming/ with @tongtybj, it is well
tested and has good documentation. Spend 5 days with that courses, and them
move to PR2 robot. Or you first teach how to set remotes and swap branches.

note that all new B4 learned everything with 16.04. They started bring up
program within robot embedded computer with indigo, but launched and used
their application program with their kinetic machine.
Of cause, you can skip kinetic and then start using 18.04 from next year,
but you have to keep answering "why we are not using 16.04.." question


--
◉ Kei Okada


2018-04-08 14:27 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by k-okada** [comment]
> Some B4 students use PR2 with kinetic in your seminar, but how do they
use it?

everyone used from kinetic, see
https://github.com/jsk-ros-pkg/jsk_demos/issues/1226 for old information
and better solution can be find
https://github.com/jsk-ros-pkg/jsk_robot/pull/898

--
◉ Kei Okada


2018-04-08 23:20 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by tongtybj** [comment]
@knorth55 

> Sorry, but since someone brakes pcl_ros, I think travis will not pass this PR until monday, So until they fixed pcl_ros, I think you can start with https://github.com/jsk-enshu/robot-programming/ with @tongtybj, it is well tested and has good documentation. Spend 5 days with that courses, and them move to PR2 robot. Or you first teach how to set remotes and swap branches. 

I will do this demo for M1 with you from tomorrow and keep improving jsk-enshu (it is my job).

**Comment by k-okada** [comment]
upstream was fixed, but test is failing 
```
pr2eus/test_results/pr2eus/rostest-test_default-ri-test.xml: 1 tests
pr2eus/test_results/pr2eus/rostest-test_make-pr2-model-file-test.xml: 1 tests
pr2eus/test_results/pr2eus/rostest-test_pr2-ri-test-simple.xml: 1 tests, 0 errors, 1 failures
pr2eus/test_results/pr2eus/rostest-test_pr2eus-test.xml: 2 tests, 0 errors, 1 failures
pr2eus/test_results/pr2eus/rostest-test_robot-init-test.xml: 1 tests
pr2eus/test_results/pr2eus/rostest-test_robot-no-clock.xml: 1 tests
pr2eus/test_results/pr2eus/rostest-test_speak-test.xml: 1 tests
pr2eus_tutorials/test_results/pr2eus_tutorials/MISSING-rostest-test_test_pr2_tabletop_sim.xml: 1 tests, 0 errors, 1 failures
```

**Comment by furushchev** [comment]
@k-okada 

Sorry for confusing, but I further updated the original pull request and merged this pull request into the original one.
Please considering to merge https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/217 instead.

**Comment by knorth55** [comment]
Move to #341 217

**Pull request closed without merging**
