### PR TITLE
more realistic simulation mode

### PR DESCRIPTION
**Pull request by k-okada**
DO NOT MERGE YET

this is another implementation of #156 , please check if this work for you @h-kamada 

this is still under development, I just tested with following scripts
```
roseus pr2-interface.l "(pr2-init)" "(send *pr2* :arms :shoulder-p :joint-angle -30)" "(send *ri* :angle-vector-sequence (list (send *pr2* :reset-manip-pose) (send *pr2* :reset-pose)))" "(print \":angle-vector done\")"  "(print (send *ri* :wait-interpolation))"
```

TODO

- :wait-interpolation-smooth
- ~~:go-pos~~, go-velocity
- add test code
- cleanup code

LIMITATION

since this uses `*job-timer*` so you have to be top-level of explicitly call `:robot-interface-simulation-callback` to move robot arm,  so it may not work within smach, please check this @furushchev

### CODE REVIEW

**Comment by h-kamada** [comment]
Ok. I'll do about this.

**Comment by h-kamada** [comment]
worked in my env.

**Comment by k-okada** [comment]
what is 'my env'? reizouko demo?

--
◉ Kei Okada

**Comment by k-okada** [comment]
I haven't support :go-pose, :wait-interapolation-smooth, but your env did
not use these function?

--
◉ Kei Okada

**Comment by h-kamada** [comment]
I don't mean it.
I checked this commit can do what I wanted to do in #156 .
Fridge demo use :go-pos function.

**Comment by k-okada** [comment]
please check with fridge demo on euslisp

--
◉ Kei Okada

**Comment by k-okada** [comment]
btw, if you run fridge demo on euslisp (without gazebo, real robot), I
think you saw a lot of
```
[ERROR] [1438838240.968802675]: "map" passed to lookupTransform argument
target_frame does not exist
```
message, but everything working well, is it correct? if so please write
issue for this. Displaying  error, but works good is confusing.

--
◉ Kei Okada

**Comment by k-okada** [comment]
added :move-to

**Comment by h-kamada** [comment]
> [ERROR] [1438838240.968802675]: "map" passed to lookupTransform argument target_frame does not exist ``` message, but everything working well, is it correct? if so please write issue for this. Displaying error, but works good is confusing.

Probably, this error message is by my mistake in jsk-ros-pkg/jsk_demos#1026 .

**Comment by k-okada** [comment]
this has been supported in 
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/140 etc...

**Pull request closed without merging**
