### PR TITLE
[pr2eus/robot-interface.l] update actionlib name of default controller.

### PR DESCRIPTION
**Pull request by mmurooka**
related to https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237#issuecomment-253728720 and https://github.com/start-jsk/rtmros_common/pull/970#issuecomment-253446024.

one of this PR or https://github.com/start-jsk/rtmros_common/pull/970 should be merged.

check result of whether hrp2jsk-init works or not:
- pr2eus (latest origin/master), hrpsys_ros_bridge (latest origin/master): not work
- pr2eus (This PR), hrpsys_ros_bridge (latest origin/master): work
- pr2eus (latest origin/master), hrpsys_ros_bridge (https://github.com/start-jsk/rtmros_common/pull/970) work

### CODE REVIEW

**Comment by mmurooka** [comment]
In my opinion, https://github.com/start-jsk/rtmros_common/pull/970 is better because of https://github.com/start-jsk/rtmros_common/pull/970#issuecomment-253518939 and https://github.com/start-jsk/rtmros_common/pull/970#issuecomment-253518939.

**Comment by mmurooka** [comment]
My opinion changed, and maybe this PR should be mearged. (and https://github.com/start-jsk/rtmros_common/pull/970 should be closed?)
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/237#issuecomment-253747327

**Comment by kyawawa** [comment]
@mmurooka https://github.com/start-jsk/rtmros_common/pull/970, はマージされていないように見えますが，どこでこれが必要になるでしょうか．

**Comment by kyawawa** [comment]
確かにこれがないと，latestのhrpsys_ros_bridge は動かない．

**Comment by kyawawa** [comment]
ああ，ちがうか．#237の影響ということか．

**Comment by mmurooka** [comment]
> ああ，ちがうか．#237の影響ということか．

そうです．

**Pull request merged**
