### PR TITLE
install pr2-send-joints.l pr2-read-state.l with original permissions

### PR DESCRIPTION
**Pull request by k-okada**
```
$ ls -al install/share/pr2eus/
total 4956
drwxrwxr-x 4 k-okada k-okada    4096 May 10 18:59 .
drwxrwxr-x 4 k-okada k-okada    4096 May 10 18:59 ..
drwxrwxr-x 2 k-okada k-okada    4096 May 10 18:59 cmake
-rw-r--r-- 1 k-okada k-okada    8436 May 10 18:56 make-pr2-model-file.l
-rw-r--r-- 1 k-okada k-okada     833 May 10 18:56 make-pr2-model-file.launch
-rw-r--r-- 1 k-okada k-okada    1870 May 10 18:56 package.xml
-rw-r--r-- 1 k-okada k-okada   35007 May 10 18:56 pr2-interface.l
-rw-r--r-- 1 k-okada k-okada 4853112 May 10 18:56 pr2.l
-----w-r-x 1 k-okada k-okada    1685 May 10 18:56 pr2-read-state.l
-rw-r--r-- 1 k-okada k-okada     171 May 10 18:56 pr2-read-state.launch
-----w-r-x 1 k-okada k-okada    1963 May 10 18:56 pr2-send-joints.l
```

### CODE REVIEW

**Comment by knorth55** [comment]
we can use ` USE_SOURCE_PERMISSIONS`, can't we?

**Comment by k-okada** [comment]
No,  USE_SOURCE_PERMISSIONS   is only available with  DIRECTORY,  we use
FILES   for there lisp scripts,
https://cmake.org/cmake/help/latest/command/install.html#installing-directories
--
◉ Kei Okada



2022年5月10日(火) 21:29 Shingo Kitagawa ***@***.***>:

**Comment by knorth55** [comment]
Thank you for your explanation, I didn't know that.

**Review by knorth55 — APPROVED** [review]

**Comment by k-okada** [comment]
thanks you , I found using `install(PROGRAMS` is also fine.

**Pull request merged**
