### PR TITLE
[pr2eus] update :go-stop for robot without move-base-trajectory-action

### PR DESCRIPTION
**Pull request by knorth55**
I update  `:go-stop` to work properly on robot without move-base-trajecotry-action.
this PR is moved from #401

### CODE REVIEW

**Comment by knorth55** [comment]
I want to add test but waiting for pr2eus move base test.
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/420

**Comment by knorth55** [comment]
I will add test for `:go-stop` in this PR.

**Comment by knorth55** [comment]
I update to add test for `:go-stop`.
@pazeshun  can you review this?

**Comment by k-okada** [comment]
Can you check if #425 ?

**Comment by knorth55** [comment]
I think #425 is good! I close this PR.

**Pull request closed without merging**
