### PR TITLE
[pr2eus] Repair :angle-vector args document

### PR DESCRIPTION
**Pull request by aginika**
From https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/85#discussion_r23537288
How can I confirmed whether the document will be made correctly or not?

### CODE REVIEW

**Comment by garaemon** [comment]
is the dic automatically generated after merging?

**Comment by k-okada** [comment]
yes, automatically generated and commit to the repo

--
◉ Kei Okada

**Comment by garaemon** [comment]
magic.


How does it work?


✉︎ Ryohei

**Comment by k-okada** [comment]
@aginika you can run make under jskeus/doc to generate pdf locally
@garaemon, see https://github.com/euslisp/jskeus/blob/master/.travis.yml#L40,
but last week I noticed travis support 'artifact' option so at least we can
send something to s3, http://docs.travis-ci.com/user/uploading-artifacts/,
they also seems to support github upload
http://docs.travis-ci.com/user/deployment/releases/, which I haven't tested
yet.

--
◉ Kei Okada

**Comment by garaemon** [comment]
Tomato bunch detection is easily done by jsk_pcl_ros

$ roslaunch jsk_pcl_ros hsi_color_filter.launch
DEFAULT_NAMESPACE:=/camera_remote_uncalibrated/depth_registered
INPUT:=points

// Of course, you need to play with several parameters

Document
* https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros#jsk_pclhsicolorfilter
* https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros#jsk_pcleuclideanclustering
* https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros#jsk_pclclusterpointindicesdecomposer
* https://github.com/jsk-ros-pkg/jsk_recognition/tree/master/jsk_pcl_ros#clusterpointindicesmsg

◉  ryohei

**Comment by snozawa** [comment]
Documentations for Euslisp/euslisp and Euslisp/jskeus are automatically generated and committed through https://github.com/euslisp/jskeus/blob/master/.travis.yml#L40.

How can we see the Euslisp documentation for pr2eus?
(related with https://github.com/start-jsk/rtmros_common/issues/601)

**Pull request merged**
