### PR TITLE
[pr2eus] Support ctype in :angle-vector-duration

### PR DESCRIPTION
**Pull request by garaemon**
@aginika Please check if this works

### CODE REVIEW

**Comment by aginika** [comment]
Ok, I will try in Baxter and PR2

**Comment by garaemon** [comment]
If it does not work, please update this PR

**Comment by garaemon** [comment]
Confirmed on PR2

**Comment by garaemon** [comment]
Please be careful about this change

**Comment by k-okada** [comment]
this will fixes #113

**Pull request merged**
