### PR TITLE
[pr2eus_moveit] Add docstring to :angle-vector-motion-plan

### PR DESCRIPTION
**Pull request by pazeshun**
Like `:angle-vector` in robot-interface.l

### CODE REVIEW

**Comment by pazeshun** [comment]
@k-okada Does this fulfill your request?

**Comment by k-okada** [comment]
```
rospkg.common.ResourceNotFound: pr2_moveit_config



                                                                                
ROS path [0]=/opt/ros/melodic/share/ros



                                                                                
ROS path [1]=/home/travis/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus_moveit



                                                                                
ROS path [2]=/home/travis/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus



                                                                                
ROS path [3]=/home/travis/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus_moveit



                                                                                
ROS path [4]=/home/travis/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus_tutorials



                                                                                
ROS path [5]=/opt/ros/melodic/share




                                                                                
Cannot find results, writing failure results to '/home/travis/ros/ws_jsk_pr2eus/build/pr2eus_moveit/test_results/pr2eus_moveit/MISSING-rostest-test_test-pr2eus-moveit.xml'
```

**Comment by k-okada** [comment]
please rebase origin/master after https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/393

**Comment by pazeshun** [comment]
@k-okada Test passed. Could you review this?

**Pull request merged**
