### PR TITLE
[pr2eus/robot-interface.l] Modified warning message in case of we can not connect to follow joint trajectory server

### PR DESCRIPTION
**Pull request by iory**
This PR modified the warning message in case of we can not connect to follow joint trajectory server,
because```goal``` topic is not always comming. 
So we should check the ```status``` topic.

### CODE REVIEW

**Comment by pazeshun** [comment]
@iory kindly ping

**Comment by iory** [comment]
I modified warn message
`make sure that you can run 'rostopic echo /~A/goal' and 'rostopic info /~A/goal'` to `make sure that you can run 'rostopic info /~A/goal'`
`

**Comment by pazeshun** [comment]
Is warn message correct?
Current implementation may allow `rostopic info` even with kinematic simulator, because robot-interface subscribes it.
Please check the behaviour.

**Comment by iory** [comment]
I modified warn message. I asked people where subscribers and publishers exist.

**Comment by iory** [comment]
Thanks you, too!

**Comment by iory** [comment]
@k-okada 
Could you please review modification of warning messages?

**Pull request merged**
