### PR TITLE
robot-interface.l: add go-* function prototype

### PR DESCRIPTION
**Pull request by k-okada**
go-* function is currently implemnted in https://github.com/jsk-ros-pkg/jsk_pr2eus/blob/master/pr2eus/pr2-interface.l#L485 or https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L713

the motivation of this PR is write template function in robot-interface.l and define API

### CODE REVIEW

**Comment by k-okada** [comment]
from @snozawa 
```
hrpsysのgoPosはnowait方式ですが、
https://github.com/fkanehiro/hrpsys-base/blob/master/idl/AutoBalancerService.idl#L195
Euslispではこれを明示的にgo-pos-no-waitとしていて、
:go-posはwaitありにしています。
https://github.com/start-jsk/rtmros_common/blob/master/hrpsys_ros_bridge/euslisp/rtm-ros-robot-interface.l#L716

このへんはむかしのpluginの時代からの歴史的な経緯でかつpr2-interface.lと同じようにするために
この状態にしています。

waitする関数はeuslispでは:wait-foot-steps
になります
```

**Comment by garaemon** [comment]
I prefer "error" instead of "warn"

**Comment by snozawa** [comment]
> I prefer "error" instead of "warn"

+1

**Comment by k-okada** [comment]
ok, updated

**Comment by snozawa** [comment]
:+1:

**Pull request merged**
