### PR TITLE
[.travis.yml] enable jade / kinetic (but allow_failure)

### PR DESCRIPTION
**Pull request by furushchev**
- enable jade / kinetic test
- move some common variables to global

### CODE REVIEW

**Comment by k-okada** [comment]
I heard jsk_travis 0.4.16 is bug embedded, https://github.com/jsk-ros-pkg/jsk_recognition/pull/1840

**Comment by k-okada** [comment]
did you intentionally update .travis ?

**Comment by furushchev** [comment]
@k-okada Sorry I could not understand what you mean.
I just wanted to migrate test environment from jenkins to travis.

**Comment by k-okada** [comment]
travis 0.4.19 had a trouble -> https://github.com/jsk-ros-pkg/jsk_travis/issues/309, and in your commit message you just write '[.travsi.yml]' so i suspect you do not want to update '.travis' submodule.
If you wan to update '.travis' submodule, I think you'd better to separate commits into to parts
```
[.travis.yml] add jenkins/kinect ....
[.travis] update to jsk_travis 0.4.20
```
so we can understand you're intentionally upgrade jsk_travis submodule.

**Comment by k-okada** [comment]
please rebase origin/master @furushchev

**Comment by furushchev** [comment]
@k-okada OK. updated along with origin/master

**Pull request merged**
