### PR TITLE
use latest travis

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by aginika** [comment]
Is there any reason this isn't merged?
I am waiting for this merging in order to merge this to my PR. https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/105#issuecomment-74677301

**Comment by k-okada** [comment]
This is old PR, you bring the code back to 6 days ago and revert 30 commits

**Comment by garaemon** [comment]
oops, i merged

**Comment by k-okada** [comment]
Ok,i'll fix this

**Comment by k-okada** [comment]
this is strage, if we look from github web pages, .travis goes to
https://github.com/jsk-ros-pkg/jsk_travis/commits/e7cd0ce8c6c00ea5579bb3533dd52a62eb58e7c7,
which is 6 days old, but if we checkout from command line, it pulls latest
one. any way create revert PR. ->
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/107

--
◉ Kei Okada

**Comment by k-okada** [comment]
Sorry this is my misunderstanding, this merge is ok, and we have to update more latest travis, so created new pr #108

**Pull request merged**
