### PR TITLE
send angle-vector only once, some controller-table had multiple definition for one method, we ignore them

### PR DESCRIPTION
**Pull request by k-okada**
rewirted version of #307
we found this is almost as same as #304

### CODE REVIEW

**Comment by knorth55** [comment]
If `:larm-head-controller``:head-controller` only have `(list head-action-client)`, this code send `:angle-vector`twice, doesn't it?
That is what I want to avoid in #304

**Comment by k-okada** [comment]
i have tested and equal check at following line skps duplicates cases, may
be because of we only have one actionlib client instance wihtin *ri*
```                           (when (and (= (length ct) 1) (equal (list
action) ct))


```
skips that situation.


--
◉ Kei Okada


2017-07-08 1:37 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
This PR sends twice in my case.

I use this branch https://github.com/knorth55/jsk_robot/tree/test for `baxtereus`.
`rarm-head-controller` and `larm-head-controller` are set as https://github.com/knorth55/jsk_robot/commit/cbb39cfe48c52ae955ff7e361fe442f7154f0f7f

```
3.irteusgl$ (send *baxter* :head_pan :joint-angle -80)
-80
4.irteusgl$ (send *baxter* :untuck-pose :rarm)
#f(-80.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 5.0 -57.0 68.0 111.0 -38.0 59.0 0.0)
5.irteusgl$ (send *baxter* :head_pan :joint-angle 80)
80
6.irteusgl$ (send *ri* :angle-vector (send *baxter* :angle-vector) 3000 :rarm-head-controller 0 :move-arm :rarm)
[ INFO] [1499586817.561381248, 814.193000000]: ;; Planned Trajectory Total Time   1.624 [sec]
[ INFO] [1499586817.561644134, 814.193000000]: ;; Scaled Trajectory Total Time   3.000 [sec]
[ INFO] [1499586817.561685640, 814.193000000]: ;; generated 12 points for 3 sec using [right_arm] group
[ INFO] [1499586817.561721440, 814.193000000]: ;; will send to (right_s0 right_s1 right_e0 right_e1 right_w0 right_w1 right_w2)
[ INFO] [1499586817.561808336, 814.193000000]: ;; action:#<controller-action-client #X5885948 /robot/head/head_action>, param:((:controller-action . /robot/head/head_action) (:controller-state . /robot/head/head_state) (:action-type . #<metaclass #X51ca760 control_msgs::singlejointpositionaction>) (:joint-names head_pan)) (4)
[ INFO] [1499586817.561925280, 814.193000000]: ;; send self :angle-vector :head-controller
[ INFO] [1499586817.564215199, 814.196000000]: ;; send self :angle-vector :larm-head-controller
[ INFO] [1499586817.564673617, 814.196000000]: ;; send self :send-trajectory :rarm-head-controller
[ WARN] [1499586817.566077820, 814.198000000]: [/robot/head/head_action] action-result-cb may recieved old client's goal
[ WARN] [1499586817.566139397, 814.198000000]:      expected goal id 814196000000_/default_robot_interface_1499586770097619834_24700_/robot/head/head_action_1
[ WARN] [1499586817.566173375, 814.198000000]:      recieved goal id 814196000000_/default_robot_interface_1499586770097619834_24700_/robot/head/head_action_0
(#f(80.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 5.0 -57.0 68.0 111.0 -38.0 59.0 0.0))
7.irteusgl$
```

**Comment by k-okada** [comment]
please check
```
(maphash #'(lambda (ac ct) (print (list ac (length ct)))) (*ri* .
controller-table))
```

larm-head-controller should return `(length ct)==2`


--
◉ Kei Okada


2017-07-09 16:57 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
`roseus jsk_arc2017_baxter/euslisp/lib/baxter-interface.l`

```
1.irteusgl$ (setq *ri* (instance jsk_arc2017_baxter::baxter-interface :init :type :rarm-controller))
[ WARN] [1499662256.455105393]: [/robot/head/head_action] action server is not found
[ WARN] [1499662256.455384932]:      goal=0, cancel=0, feedback=0, result=0
[ WARN] [1499662256.455536906]: #<controller-action-client #X24c00848 /robot/head/head_action> is not respond, baxter-interface is disabled
[ WARN] [1499662256.455624467]: Starting 'Kinematics Simulator'
[ WARN] [1499662256.455798256]:  (If you do not intend to start Kinematics Simulator, make sure that you can run 'rostopic echo //robot/head/head_action/goal' and 'rostopic info //robot/head/head_action/goal')
((lambda nil (send #<jsk_arc2017_baxter::baxter-interface #X65e1250> :robot-interface-simulation-callback)) lisp::count-up-timer)
[ WARN] [1499662256.632319303]: #<ros::simple-action-client #X252b3078 robot/end_effector/right_gripper/gripper_action> is not respond
[ INFO] [1499662256.632373662]: *** if you do not have gripper, you can ignore this message ***
[ WARN] [1499662256.648006067]: #<ros::simple-action-client #X252ad1f8 /gripper_front/limb/right/hand/follow_joint_trajectory> is not respond
[ INFO] [1499662256.648049987]: *** if you do not have hand, you can ignore this message ***
#<jsk_arc2017_baxter::baxter-interface #X65e1250>
2.irteusgl$ (maphash #'(lambda (ac ct) (print (list ac (length ct)))) (*ri* . controller-table))
(:rarm-controller 3)
(:larm-controller 1)
(:head-controller 1)
(:larm-no-gripper-controller 0)
(:lgripper-controller 0)
(:no-gripper-controller 1)
(:rgripper-controller 1)
(:rarm-no-gripper-controller 1)
nil
3.irteusgl$ 
```

**Comment by k-okada** [comment]
> :head-controller,  :larm-head-controller

why we do not have :larm-head-controller ?

--
◉ Kei Okada


2017-07-10 13:52 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
In `jsk_arc2017_baxter`, we override `larm-controller` as `larm-head-controller`.
so, in this code, `:larm-controller` is equal to `larm-head-controller`.

**Comment by k-okada** [comment]
I see, fixed, please check on your environment @knorth55

**Comment by knorth55** [comment]
```
1.irteusgl$ (baxter-init :type :rarm-head-controller)
[ WARN] [1499690742.803651119, 346.057000000]: [/default_robot_interface_1499690742286627839] waiting /clock... 0.003188 seconds elapsed.
[ INFO] [1499690742.803747702, 346.057000000]: [/default_robot_interface_1499690742286627839] /clock is now published.
[ WARN] [1499690746.181933907, 349.429000000]: [robot/end_effector/right_gripper/gripper_action] action server is not found
[ WARN] [1499690746.182034427, 349.429000000]:      goal=0, cancel=0, feedback=0, result=0
[ WARN] [1499690746.182074716, 349.429000000]: #<ros::simple-action-client #X654eb60 robot/end_effector/right_gripper/gripper_action> is not respond
[ INFO] [1499690746.182097297, 349.429000000]: *** if you do not have gripper, you can ignore this message ***
nil
2.irteusgl$ (send *ri* :angle-vector-raw (send *baxter* :reset-pose :rarm))
(#f(0.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 -20.0 -25.0 40.0 60.0 20.0 80.0 0.0))
3.irteusgl$ (send *baxter* :head_pan :joint-angle 80)
80
4.irteusgl$ (send *baxter* :untuck-pose :rarm)
#f(80.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 5.0 -57.0 68.0 111.0 -38.0 59.0 0.0)
5.irteusgl$ (send *ri* :angle-vector (send *baxter* :angle-vector) 3000 :rarm-head-controller 0 :move-arm :rarm)
[ INFO] [1499690821.138454630, 424.172000000]: ;; Planned Trajectory Total Time   1.626 [sec]
[ INFO] [1499690821.138669691, 424.172000000]: ;; Scaled Trajectory Total Time   1.626 [sec]
[ INFO] [1499690821.138696039, 424.172000000]: ;; generated 12 points for 1.62561 sec using [right_arm] group
[ INFO] [1499690821.138714859, 424.172000000]: ;; will send to (right_s0 right_s1 right_e0 right_e1 right_w0 right_w1 right_w2)
[ INFO] [1499690821.138785322, 424.172000000]: ;; action:#<controller-action-client #X6a88c10 /robot/head/head_action>, param:((:controller-action . /robot/head/head_action) (:controller-state . /robot/head/head_state) (:action-type . #<metaclass #X63cd760 control_msgs::singlejointpositionaction>) (:joint-names head_pan)) (4)
[ INFO] [1499690821.138833919, 424.172000000]: ;; send self :angle-vector :head-controller (#<controller-action-client #X6a88c10 /robot/head/head_action>)
[ INFO] [1499690821.144045125, 424.177000000]: ;; send self :send-trajectory :rarm-head-controller
(#f(80.0 20.0 -25.0 -40.0 60.0 -20.0 80.0 0.0 5.0 -57.0 68.0 111.0 -38.0 59.0 0.0))
```

**Comment by knorth55** [comment]
@k-okada it works! thank you!

**Pull request merged**
