### PR TITLE
[pr2eus] change-inflation-range to use new service name

### PR DESCRIPTION
**Pull request by aginika**
This change is for after hydro.

### CODE REVIEW

**Comment by k-okada** [comment]
does hydro uses `move_base_node/local_costmap/set_parameters` or `/move_base_node/local_costmap/inflation/set_parameters`

**Comment by aginika** [comment]
At least, PR2 is working with `/move_base_node/local_costmap/inflation/set_parameters`

**Comment by k-okada** [comment]
is that hydro ? or indigo?

--
◉ Kei Okada

**Comment by furushchev** [comment]
@k-okada in hydro, if you set old-style param, then `move_base_node/local_costmap/set_parameters` for back compatibility.
recently I changed it to new-style, and it uses `/move_base_node/local_costmap/inflation/set_parameters`

**Comment by aginika** [comment]
@k-okada Sorry, PR2 is now working in hydro

**Comment by k-okada** [comment]
On Mon, Sep 7, 2015 at 3:38 PM, Furushchev <notifications@github.com> wrote:

> I changed it to new-style,


please paste ink to this change

--
◉ Kei Okada

**Comment by furushchev** [comment]
PR is https://github.com/jsk-ros-pkg/jsk_robot/pull/358
about change of api/param is noted in section 8.1.1 at http://wiki.ros.org/costmap_2d

**Pull request merged**
