### PR TITLE
[pr2eus_moveit] modify :angle-vector-motion-plan to accept angle-vector-sequence

### PR DESCRIPTION
**Pull request by knorth55**
### What Changed:

- modify `:angle-vector-motion-plan` to accept angle-vector-sequence
- set `(butlast avs)` as trajectory constraints

I checked with real robot and it works

### CODE REVIEW

**Comment by knorth55** [comment]
@k-okada ping. please make a review and merge this?

**Comment by k-okada** [comment]
do you think you can write something like `if (listp av) ...`

--
◉ Kei Okada


2016-11-21 20:24 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
i added `listp` check as below 
https://github.com/knorth55/jsk_pr2eus/blob/1b02307d902ae9c94ec8e1a77d2b268dd5e319c5/pr2eus_moveit/euslisp/robot-moveit.l#L496-L498

**Comment by k-okada** [comment]
oh, I mean without :set-angle-vector-sequence

--
◉ Kei Okada


2016-11-21 21:48 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
like this? https://github.com/knorth55/jsk_pr2eus/blob/3a2526964d208f9c93f6bdcf7149f399dfa3cc06/pr2eus_moveit/euslisp/robot-moveit.l#L320-L321

**Comment by knorth55** [comment]
i added listp check and warning in `:angle-vector-motion-plan`, too
https://github.com/knorth55/jsk_pr2eus/blob/25d95bc4874bdebea7b3a564aecf8653796ab3b2/pr2eus_moveit/euslisp/robot-moveit.l#L510-L512

**Comment by knorth55** [comment]
@k-okada ping.

**Comment by knorth55** [comment]
Please merge this

**Comment by knorth55** [comment]
@k-okada ping. please merge this.

**Comment by k-okada** [comment]
Is removing :set-angle-vector-sequence difficult?

2016年11月25日(金) 10:16 Shingo Kitagawa <notifications@github.com>:

**Comment by knorth55** [comment]
@k-okada I updated and remove `:set-angle-vector-sequence`

**Comment by k-okada** [comment]
Thanks, may be we do not need `:angle-vector-sequence-motion-plan` any more, `:angle-vector-motion-plan` accepts both atom and list

**Comment by knorth55** [comment]
@k-okada ok, i remove `angle-vector-sequence-motion-plan`, and now `angle-vector-motion-plan` accepts both atom and list.

**Comment by k-okada** [comment]
thanks

--
◉ Kei Okada


2016-11-27 0:48 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Pull request merged**
