### PR TITLE
[pr2eus_moveit] add 0.5 seconds sleep after collision object pub

### PR DESCRIPTION
**Pull request by knorth55**
According to moveit tutorials, we need to put sleep after topic publishing.
I have several reports that it sometimes fails to wipe all scenes.

http://docs.ros.org/indigo/api/pr2_moveit_tutorials/html/planning/src/doc/planning_scene_ros_api_tutorial.html

### CODE REVIEW

**Comment by knorth55** [comment]
adding `unix::usleep` is not smart solution, but I couldn't find out better solution.

**Comment by k-okada** [comment]
please add following comment within source code
```
According to moveit tutorials, we need to put sleep after topic publishing.
http://docs.ros.org/indigo/api/pr2_moveit_tutorials/html/planning/src/doc/planning_scene_ros_api_tutorial.html
adding unix::usleep is not smart solution, but I couldn't find out better
solution.
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/315#issuecomment-315015718
```

--
◉ Kei Okada


2017-07-13 17:54 GMT+09:00 Shingo Kitagawa <notifications@github.com>:

**Comment by k-okada** [comment]
added comment

**Comment by knorth55** [comment]
Thank you!

**Pull request merged**
