### PR TITLE
Fix bug on joint-move-over-180 with tm :fast

### PR DESCRIPTION
**Pull request by Affonso-Gui**
On pr2, calls to `:angle-vector` with time as `:fast` lead to `number expected` errors when `:check-continuous-joint-move-over-180` is true.

This PR avoids this by setting all the sub-times as `:fast` in this case.

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
@k-okada Can I ask for a review?

**Comment by Affonso-Gui** [comment]
@knorth55

**Comment by k-okada** [comment]
Can we add test code to catch this?

**Comment by Affonso-Gui** [comment]
@k-okada Added.

**Comment by Affonso-Gui** [comment]
@k-okada Tests pass/fail as expected. Can we merge this?

**Pull request merged**
