### PR TITLE
enable pr2 tabletop demo

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by furushchev** [comment]
Now cleaning commits.
Please dont merge.

**Comment by furushchev** [comment]
ok to merge

**Comment by k-okada** [comment]
ok, so let's make how-to documents, and ask @iKrishneel to check that
program as well as English.

--
◉ Kei Okada

**Comment by iKrishneel** [comment]
Thanks I actual needed this demo. 
Also is there any demo for collision avoidance check with other bounding boxes during grasping?

**Comment by furushchev** [comment]
@iKrishneel Added launch file and sample code of pr2_tabletop demo, which will be merged soon. Please check https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/217. For collision avoidance you may need to try pr2_moveit. I'm also interested in using moveit with pr2, and will try it.

**Comment by k-okada** [comment]
On Fri, Apr 8, 2016 at 6:26 PM, Krishneel <notifications@github.com> wrote:

> Also is there any demo for collision avoidance check with other bounding
> boxes during grasping?
>
>
you can first try to move the robot without care about collision and take a
video, usually there are nice "preparing posture" for grasping that works
for most of caes.

--
◉ Kei Okada

**Pull request merged**
