### PR TITLE
- need to call roseus at the end of find_package so that roseus.cmake can read all package files

### PR DESCRIPTION
**Pull request by k-okada**

### CODE REVIEW

**Comment by garaemon** [comment]
oops , sorry I merged colliding pull request.
Please merge origin/master

**Comment by k-okada** [comment]
sound_play is already set in -> https://github.com/k-okada/jsk_pr2eus/blob/fix_compile/pr2eus/catkin.cmake#L13

**Comment by garaemon** [comment]
I see, I understand finally that location of roseus is the most important.

**Comment by garaemon** [comment]
After that, could you release newer version?

**Pull request merged**
