### PR TITLE
[.travis] update to latest

### PR DESCRIPTION
**Pull request by furushchev**
This fix recent build error
https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/199#issuecomment-165013548

### CODE REVIEW

**Comment by furushchev** [comment]
test failed on indigo.

```
[pr2eus] -- run_tests.py: execute commands                                      

[pr2eus]   /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/workspace/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus --package=pr2eus --results-filename test_robot-no-clock.xml --results-base-dir /workspace/ros/ws_jsk_pr2eus/build/pr2eus/test_results /workspace/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus/test/robot-no-clock.test 

[pr2eus] INFO: cannot create a symlink to latest log directory: [Errno 17] File exists 

[pr2eus] INFO: cannot create a symlink to latest log directory: [Errno 17] File exists 

[pr2eus] INFO: cannot create a symlink to latest log directory: [Errno 17] File exists 

[pr2eus] INFO: cannot create a symlink to latest log directory: [Errno 17] File exists 

[pr2eus] INFO: cannot create a symlink to latest log directory: [Errno 17] File exists 

[pr2eus] ... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-58694aec1a3b-10013.log 

[pr2eus] ... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-58694aec1a3b-10015.log 

[pr2eus] ... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-58694aec1a3b-10014.log 

[pr2eus] ... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-58694aec1a3b-10016.log 

[pr2eus] ... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-58694aec1a3b-10010.log 

[pr2eus] ... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-58694aec1a3b-10009.log 

[pr2eus] [ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_pr2eus/build/pr2eus/test_results/pr2eus/rostest-test_pr2-ri-test-simple.xml 

[pr2eus] Traceback (most recent call last):                                     

[pr2eus]   File "/opt/ros/indigo/share/rostest/cmake/../../../bin/rostest", line 36, in  

[pr2eus]     rostestmain()                                                      

[pr2eus]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain 

[pr2eus]     _main()                                                            

[pr2eus]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 167, in rostestmain 

[pr2eus]     results_file = xmlResultsFile(pkg, outname, is_rostest, env=env)   

[pr2eus]   File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/core.py", line 102, in xml_results_file 

[pr2eus]     raise IOError("cannot create test results directory [%s]. Please check permissions."%(test_dir)) 

[pr2eus] IOError: cannot create test results directory [/workspace/ros/ws_jsk_pr2eus/build/pr2eus/test_results/pr2eus]. Please check permissions. 
```

**Comment by furushchev** [comment]
please do not merge now

**Comment by furushchev** [comment]
Travis failed on `rosdep install`.
Need to fix `jsk_travis`?

```bash
+ rosdep install -r -q -n --from-paths . /opt/ros/indigo/share --ignore-src --rosdistro indigo -y
executing command [sudo -H apt-get install -y -qq ros-indigo-sound-play]
WARNING: The following packages cannot be authenticated!
  libgudev-1.0-0 libsoup-gnome2.4-1 gstreamer0.10-plugins-base
  gstreamer0.10-plugins-good libdvdread4 libdvdnav4 libestools2.1 libmad0
  libmpeg2-4 libopencore-amrnb0 libopencore-amrwb0 festival festlex-cmu
  festlex-poslex liba52-0.7.4 libcdio13 libsidplay1 libtwolame0
  gstreamer0.10-plugins-ugly gstreamer0.10-x python-gobject python-libxml2
  python-gst0.10 festvox-kallpc16k ros-indigo-audio-common-msgs
  ros-indigo-sound-play
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq python-mock]
WARNING: The following packages cannot be authenticated!
  python-mock
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-euscollada]
WARNING: The following packages cannot be authenticated!
  collada-dom2.4-sp-base ros-indigo-assimp-devel ros-indigo-euscollada
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-pr2-msgs]
WARNING: The following packages cannot be authenticated!
  ros-indigo-pr2-msgs
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-pr2-description]
WARNING: The following packages cannot be authenticated!
  ros-indigo-xacro ros-indigo-pr2-description
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-pr2-controllers-msgs]
WARNING: The following packages cannot be authenticated!
  ros-indigo-pr2-controllers-msgs
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq python-coverage]
WARNING: The following packages cannot be authenticated!
  libjs-jquery-hotkeys javascript-common libjs-jquery-metadata
  libjs-jquery-tablesorter python-coverage libjs-jquery-isonscreen
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-move-base-msgs]
WARNING: The following packages cannot be authenticated!
  ros-indigo-move-base-msgs
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-roseus]
WARNING: The following packages cannot be authenticated!
  xfonts-100dpi xfonts-75dpi ros-indigo-actionlib-tutorials ros-indigo-euslisp
  ros-indigo-geneus ros-indigo-jskeus ros-indigo-roseus
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq libcppunit-dev]
WARNING: The following packages cannot be authenticated!
  libcppunit-1.13-0 libcppunit-dev
E: There are problems and -y was used without --force-yes
executing command [sudo -H apt-get install -y -qq ros-indigo-moveit-resources]
WARNING: The following packages cannot be authenticated!
  ros-indigo-moveit-resources
E: There are problems and -y was used without --force-yes
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y -qq ros-indigo-sound-play] failed
  apt: command [sudo -H apt-get install -y -qq python-mock] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-euscollada] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-pr2-msgs] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-pr2-description] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-pr2-controllers-msgs] failed
  apt: command [sudo -H apt-get install -y -qq python-coverage] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-move-base-msgs] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-roseus] failed
  apt: command [sudo -H apt-get install -y -qq libcppunit-dev] failed
  apt: command [sudo -H apt-get install -y -qq ros-indigo-moveit-resources] failed
  apt: Failed to detect successful installation of [ros-indigo-sound-play]
  apt: Failed to detect successful installation of [python-mock]
  apt: Failed to detect successful installation of [ros-indigo-euscollada]
  apt: Failed to detect successful installation of [ros-indigo-pr2-msgs]
  apt: Failed to detect successful installation of [ros-indigo-pr2-description]
  apt: Failed to detect successful installation of [ros-indigo-pr2-controllers-msgs]
  apt: Failed to detect successful installation of [python-coverage]
  apt: Failed to detect successful installation of [ros-indigo-move-base-msgs]
  apt: Failed to detect successful installation of [ros-indigo-roseus]
  apt: Failed to detect successful installation of [libcppunit-dev]
  apt: Failed to detect successful installation of [ros-indigo-moveit-resources]
```

**Comment by k-okada** [comment]
because of using proxy?

(time due to speed up by proxy ) < (time need to debug because of using
proxy) ???

--
◉ Kei Okada

**Comment by garaemon** [comment]
You need https://github.com/jsk-ros-pkg/jsk_travis/pull/222

Update .travis again

**Comment by furushchev** [comment]
maybe need to tagging? Is it allowed to update `.travis` to untagged revision?

**Comment by garaemon** [comment]
release jsk_travis is too difficult for me
https://github.com/jsk-ros-pkg/jsk_travis/issues/218

Because it needs indigo.

@k-okada Could you relase jsk_travis?

**Comment by furushchev** [comment]
@garaemon So for now I update `.travis` to latest, ok?

**Comment by garaemon** [comment]
yes, please update

**Comment by furushchev** [comment]
ok, now I found that the error is from `collada_urdf`.

```bash
rosrun collada_urdf urdf_to_collada /tmp/pr2_23554.urdf /tmp/hogehoge.dae
[ WARN] [1450616865.667207296]: failed to load resource package://pr2_description/meshes/sensors/kinect_prosilica_v0/115x100_swept_back--coarse.STL
I/O error : No such file or directory
I/O error : No such file or directory
error : xmlNewTextWriterFilename : cannot open uri

Document successfully written to /tmp/hogehoge.dae
```

It actually does not create the collada file output, and test failed.
This is maybe bug?

ref:
http://answers.ros.org/question/173432/conversion-from-urdf-to-dae-fails-while-attempting-to-install-ikfast-for-ur5/
http://answers.ros.org/question/198995/problem-converting-simple-urdf-file-in-collada/

**Comment by k-okada** [comment]
that has been fixed by
https://github.com/ros/robot_model/issues/118#issuecomment-164554380

--
◉ Kei Okada

**Comment by furushchev** [comment]
ok now travis passed. we can go ahead.

**Comment by furushchev** [comment]
@k-okada Thanks!

**Pull request merged**
