### PR TITLE
[pr2eus/speak.l] add speak backward compatibility

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by k-okada** [comment]
Add test 

--
◉ Kei Okada

2015/11/18 15:44、Furushchev <notifications@github.com> のメッセージ:

**Comment by furushchev** [comment]
I think the test proposed at #185 catches this PR.

**Comment by k-okada** [comment]
please add this pr on the top of #185 so that you can confirm the failure
on #185 is fixed by this PR

--
◉ Kei Okada

**Comment by furushchev** [comment]
cherry-picked test codes from #185.
Now passed test on hydro, but still fail in indigo

```bash
next build number is 199
wait for trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true 199
start building, wait for result....
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true/199/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true/199/ building.. True result... None
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true/199/ building.. True result... None
Traceback (most recent call last):
  File "./.travis/travis_jenkins.py", line 311, in 
    print j.get_build_console_output(job_name, build_number)
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 1196, in get_build_console_output
    self._build_url(BUILD_CONSOLE_OUTPUT, locals())
  File "/home/travis/.local/lib/python2.7/site-packages/jenkins/__init__.py", line 346, in jenkins_open
    return response.decode('utf-8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf7 in position 407468: invalid start byte
```

Maybe jenkins fails when output includes non ascii characters?

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/trusty-travis-jsk-ros-pkg-jsk_pr2eus-indigo-deb-true/199/console
```
).^[0m
failed ... ( ^[0mmstar).
testspeak_test_node ... ok

Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py",
line 268, in rostestmain
    _main()
  File
"/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line
196, in rostestmain
    printRostestSummary(result, subtest_results)
  File
"/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostestutil.py", line
75, in printRostestSummary
    return rosunit.print_runner_summary(result, rostest_results,
runner_name='ROSTEST')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/baretest.py",
line 480, in print_runner_summary
    buff.write(tc_result.description)
UnicodeEncodeError: 'ascii' codec can't e
```
need to fix rostest/rosunit too

```
[ERROR] [1447908382.137477875]: action server /robotsound is not found.
sound_play node is not alive?
[ERROR] test (speak-en hello, world) failed ... ( ^[0mmstart testing
[test-speak-en]
_results/pr2eus/rosunit-speak_test_node.xml
20:12 UTC 2015  1.0.11))
�� ).
[ERROR] [1447908402.255861657]: action server /robotsound is not found.
sound_play node is not alive?
[ERROR] test (speak-en hello, world :wait t) failed ... ( e.xml
20:12 UTC 2015  1.0.11))
�� ).^[0m
failed ... ( ^[0mmstart testing [test-speak-en]
_results/pr2eus/rosunit-speak_test_nod).
[ERROR] [1447908422.374197408]: action server /robotsound is not found.
sound_play node is not alive?
[ERROR] test (speak-en hello, world :google t) failed ... (  testing
[test-speak-en]
_results/pr2eus/rosunit-speak_test_nod).^[0m
0:12 UTC 2015  1.0.11))
�� ).^[0m
failed ... ( ^[0mmstart).
```
is this expected behavior?

--
◉ Kei Okada

**Comment by furushchev** [comment]
This is NOT expected.

on my indigo env (docker, only intalled jsk_pr2eus, jsk_demos from source, and others are installed by apt-get (ros release) )
this test passes.
maybe apt package is not the latest on jenkins?

```
start testing [test-speak-en]
start testing [test-speak-jp]
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
start testing [test-speak-google]
SIOD ERROR: unbound variable : aq_rm.phont
[ERROR] [WallTime: 1447914963.301852] Sound synthesis failed. Is festival installed? Is a festival voice installed? Try running "rosdep satisfy sound_play|sh". Refer to http://pr.willowgarage.com/wiki/sound_play/Troubleshooting
SIOD ERROR: unbound variable : aq_rm.phont
[ERROR] [WallTime: 1447914963.365267] Sound synthesis failed. Is festival installed? Is a festival voice installed? Try running "rosdep satisfy sound_play|sh". Refer to http://pr.willowgarage.com/wiki/sound_play/Troubleshooting
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
testspeak_test_node ... ok

[ROSTEST]-----------------------------------------------------------------------

[pr2eus.rosunit-speak_test_node/all-test][passed]
[pr2eus.rosunit-speak_test_node/test-speak-en][passed]
[pr2eus.rosunit-speak_test_node/test-speak-jp][passed]
[pr2eus.rosunit-speak_test_node/test-speak-google][passed]

SUMMARY
 * RESULT: SUCCESS
 * TESTS: 3
 * ERRORS: 0
 * FAILURES: 0
```

**Comment by furushchev** [comment]
in my docker version of sound_play is 0.2.7

```bash
$ rosversion sound_play
0.2.7
leus@05e1621865bf:~/ros/indigo/src/audio_common$ sudo aptitude show ros-indigo-sound-play
Package: ros-indigo-sound-play           
State: installed
Automatically installed: no
Version: 0.2.7-1trusty-20150522-2112-+0000
```

but in jenkins it seems 0.2.8:

```bash
Unpacking ros-indigo-audio-common-msgs (0.2.8-0trusty-20151110-2353-+0000) ...
Selecting previously unselected package ros-indigo-sound-play.
Preparing to unpack .../ros-indigo-sound-play_0.2.8-0trusty-20151111-0453-+0000_amd64.deb ...
Unpacking ros-indigo-sound-play (0.2.8-0trusty-20151111-0453-+0000) ...
```

I installed 0.2.8 from source, then the same error as jenkins occurs!

```bash
$ rostest speak-test.test 
... logging to /home/leus/.ros/log/rostest-05e1621865bf-10452.log
[ROSUNIT] Outputting test results to /home/leus/.ros/test_results/pr2eus/rostest-test_speak-test.xml
configuring by "/opt/ros/indigo/share/euslisp/jskeus/eus//lib/eusrt.l"
;; readmacro ;; object ;; packsym ;; common ;; constants ;; stream ;; string ;; loader ;; pprint ;; process ;; hashtab ;; array ;; mathtran ;; eusdebug ;; eusforeign ;; coordinates ;; tty ;; history ;; toplevel ;; trans ;; comp ;; builtins ;; par ;; intersection ;; geoclasses ;; geopack ;; geobody ;; primt ;; compose ;; polygon ;; viewing ;; viewport ;; viewsurface ;; hid ;; shadow ;; bodyrel ;; dda ;; helpsub ;; eushelp ;; xforeign ;; Xdecl ;; Xgraphics ;; Xcolor ;; Xeus ;; Xevent ;; Xpanel ;; Xitem ;; Xtext ;; Xmenu ;; Xscroll ;; Xcanvas ;; Xtop ;; Xapplwin 
;; pixword ;; RGBHLS ;; convolve ;; piximage ;; pbmfile ;; image_correlation ;; oglforeign ;; gldecl ;; glconst ;; glforeign ;; gluconst ;; gluforeign ;; glxconst ;; glxforeign ;; eglforeign ;; eglfunc ;; glutil ;; gltexture ;; glprim ;; gleus ;; glview ;; toiv-undefined ;; fstringdouble irtmath irtutil irtc irtgeoc irtgraph pgsql irtgeo euspqp pqp irtscene irtmodel irtdyna irtrobot irtsensor irtbvh irtcollada irtpointcloud irtx eusjpeg euspng png irtimage irtglrgb 
;; extending gcstack 0x56efd30[16374] --> 0x5b24980[32748] top=3f7f
irtgl irtviewer 
EusLisp 9.15( 1.0.10) for Linux64 created on host02.storm.ros.org(Mon Aug 31 15:37:47 UTC 2015)
roseus ;; loading roseus("") on euslisp((9.15 host02.storm.ros.org Mon Aug 31 15:37:47 UTC 2015  1.0.10))
eustf /home/leus/ros/indigo/src/audio_common/sound_play/scripts/soundplay_node.py:376: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.diagnostic_pub = rospy.Publisher("/diagnostics", DiagnosticArray)
/home/leus/ros/indigo/src/audio_common/sound_play/scripts/soundplay_node.py:376: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.diagnostic_pub = rospy.Publisher("/diagnostics", DiagnosticArray)
roseus_c_util output to /home/leus/.ros/test_results/pr2eus/rosunit-speak_test_node.xml
start testing [test-speak-en]
[ERROR] [1447916400.535196370]: action server /robotsound is not found. sound_play node is not alive?
[ERROR] test (speak-en hello, world) failed ... ( mstart testing [test-speak-en]
_results/pr2eus/rosunit-speak_test_node.xml
37:47 UTC 2015  1.0.10))
gn).
[ERROR] [1447916420.657502784]: action server /robotsound is not found. sound_play node is not alive?
[ERROR] test (speak-en hello, world :wait t) failed ... ( e.xml
37:47 UTC 2015  1.0.10))
gn).
failed ... ( mstart testing [test-speak-en]
_results/pr2eus/rosunit-speak_test_nod).
[ERROR] [1447916440.779871276]: action server /robotsound is not found. sound_play node is not alive?
[ERROR] test (speak-en hello, world :google t) failed ... (  testing [test-speak-en]
_results/pr2eus/rosunit-speak_test_nod).
7:47 UTC 2015  1.0.10))
gn).
failed ... ( mstart).
start testing [test-speak-jp]
[ERROR] [1447916460.911722312]: action server /robotsound_jp is not found. sound_play node is not alive?
[ERROR] test (speak-jp こんにちは) failed ... ( mstart testing [test-speak-jp]
).
failed ... ( mstart).
g [test-speak-en]
_results/pr2eus/rosunit-speak_test_nod).
[ERROR] [1447916481.034129961]: action server /robotsound_jp is not found. sound_play node is not alive?
[ERROR] test (speak-jp こんにちは :wait t) failed ... ( m
g [test-speak-en]
_results/pr2eus/rosunit-speak_test_nod).
art testing [test-speak-jp]
).
failed ... ( mstart).[0).
[ERROR] [1447916501.158876001]: action server /robotsound is not found. sound_play node is not alive?
[ERROR] test (speak-jp こんにちは :google t) failed ... ( 0m
art testing [test-speak-jp]
).
failed ... ( mstart).[0).
st-speak-en]
_results/pr2eus/rosunit-speak_test_nod).[).
start testing [test-speak-google]
[ERROR] [1447916521.282708497]: action server /robotsound is not found. sound_play node is not alive?
[ERROR] test (speak-google bonjour :lang :fr) failed ... ( mstart testing [test-speak-google]
us/rosunit-speak_test_nod).[).
testing [test-speak-jp]
).
failed ... ( mstar).
testspeak_test_node ... ok

Traceback (most recent call last):
  File "/opt/ros/indigo/bin/rostest", line 36, in <module>
    rostestmain()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/__init__.py", line 268, in rostestmain
    _main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostest_main.py", line 187, in rostestmain
    printRostestSummary(result, subtest_results)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rostest/rostestutil.py", line 75, in printRostestSummary
    return rosunit.print_runner_summary(result, rostest_results, runner_name='ROSTEST')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosunit/baretest.py", line 480, in print_runner_summary
    buff.write(tc_result.description)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 97-101: ordinal not in range(128)
```

**Comment by k-okada** [comment]
you can check if that works with latest sources with USE_DEB=false

--
◉ Kei Okada

**Comment by furushchev** [comment]
I found that it does not works on latest sound_play without remapping.
So I'll update test scripts.
Also test with `:wait t` always fails because container on travis/jenkins has no speaker. (without speaker, sound_play outputs error to action client.)

**Comment by k-okada** [comment]
https://github.com/ros-drivers/audio_common/commit/364a19c792237cb4fd4d5b12ebd2b73208f0cea2
?

--
◉ Kei Okada

**Comment by furushchev** [comment]
I think it is not actually tested yet, doesn't it?...

```bash
  /opt/ros/indigo/share/rostest/cmake/../../../bin/rostest --pkgdir=/workspace/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus --package=pr2eus --results-filename test_speak-test.xml --results-base-dir /workspace/ros/ws_jsk_pr2eus/build/pr2eus/test_results /workspace/ros/ws_jsk_pr2eus/src/jsk_pr2eus/pr2eus/test/speak-test.test 


INFO: cannot create a symlink to latest log directory: [Errno 17] File exists


INFO: cannot create a symlink to latest log directory: [Errno 17] File exists


INFO: cannot create a symlink to latest log directory: [Errno 17] File exists


INFO: cannot create a symlink to latest log directory: [Errno 17] File exists


INFO: cannot create a symlink to latest log directory: [Errno 17] File exists


... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-ef2b59cf8156-9906.log


... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-ef2b59cf8156-9904.log


... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-ef2b59cf8156-9909.log


... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-ef2b59cf8156-9905.log


... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-ef2b59cf8156-9907.log


... logging to /workspace/jsk-ros-pkg/jsk_pr2eus/log/rostest-ef2b59cf8156-9908.log


[ROSUNIT] Outputting test results to /workspace/ros/ws_jsk_pr2eus/build/pr2eus/test_results/pr2eus/rostest-test_speak-test.xml
```

**Comment by furushchev** [comment]
sorry it was my mistake. now updated.

**Pull request merged**
