### PR TITLE
[pr2eus_moveit] Catkinize pr2eus_moveit

### PR DESCRIPTION
**Pull request by aginika**
When I `catkin build`, this will not generate the manifest.l.
What should I do to invoke it ?

### CODE REVIEW

**Comment by k-okada** [comment]
I think manifest.l is generated,
https://travis-ci.org/jsk-ros-pkg/jsk_pr2eus/jobs/51074612#L3537,
https://travis-ci.org/jsk-ros-pkg/jsk_pr2eus/jobs/51074612#L5463
also please merge https://github.com/jsk-ros-pkg/jsk_pr2eus/pull/106

--
◉ Kei Okada

**Comment by k-okada** [comment]
Please merge... is wrong , please rebase origin/maste

**Comment by aginika** [comment]
Just I need to do is, on catkin-pr2eus-moveit branch,
```
git rebase master
```
?
Why did I need this time?

**Comment by k-okada** [comment]
because we want to test code on latest travis, I found many bugs on the
.travis last weekend
https://github.com/jsk-ros-pkg/jsk_travis/commits/master

--
◉ Kei Okada

**Comment by aginika** [comment]
Thank you.
I did above command and pushed.

**Pull request merged**
